"use client"; // Uses framer-motion for hero animation, video element, and scroll listener

import { useState, useRef, useLayoutEffect, useEffect } from "react";
import Image from "next/image";
import imageLoader from "@/lib/image-loader";
import { versionedAsset } from "@/lib/site";
import { m } from "framer-motion";
import { Pause, Play } from "lucide-react";
import type { HeroData } from "@/lib/types";
import { useLanguage } from "@/lib/language-context";

interface HeroImageProps {
  hero: HeroData;
}

const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH || "";

// Candidate widths for the art-directed poster srcset, capped at each source's native width
// (mobile clip is portrait, 720w max; desktop is landscape, 1920w max) to avoid upscaling.
const MOBILE_WIDTHS = [360, 480, 640, 720];
const DESKTOP_WIDTHS = [828, 1080, 1280, 1600, 1920];

// Build a CDN srcset for the hero poster. next/image can't art-direct (one src across all
// viewports), so the poster lives in a <picture> and its srcset is generated by hand — URLs
// still flow through the Netlify Image CDN via imageLoader (pass-through in dev).
function heroSrcSet(src: string, widths: number[]): string {
  return widths.map((w) => `${imageLoader({ src, width: w, quality: 78 })} ${w}w`).join(", ");
}


export function HeroImage({ hero }: HeroImageProps) {
  const [paused, setPaused] = useState(false);
  const [atTop, setAtTop] = useState(true);
  const sectionRef = useRef<HTMLElement>(null);

  // Show the hero content ONLY in the pristine top state, defined as "the hero
  // section still covers the entire viewport". Checking scroll position alone
  // (scrollY, or a top sentinel) misses the mobile URL-bar phase: the first
  // ~56px of finger travel collapse the toolbar WITHOUT scrolling the page —
  // scrollY stays 0 while the viewport grows past the section's svh height and
  // the next section peeks in from the bottom, so the user has visually "left
  // the top" yet every scroll-based check still says top. Comparing the
  // section's bottom edge against the live viewport height catches both real
  // scrolling and that toolbar zone, in one synchronous geometry read per event
  // (rAF-throttled) — measurement and decision in the same frame, no IO/scrollY
  // race. (scroll is listened on document with capture so any scroller is
  // caught; resize + visualViewport resize cover toolbar viewport changes that
  // emit no scroll event. The 2px slack absorbs DPR rounding.)
  useEffect(() => {
    const section = sectionRef.current;
    if (!section) return;

    let raf = 0;
    const update = () => {
      raf = 0;
      setAtTop(section.getBoundingClientRect().bottom >= window.innerHeight - 2);
    };
    const schedule = () => {
      if (!raf) raf = requestAnimationFrame(update);
    };
    update(); // sync initial state on reload (e.g. restored scroll position)

    document.addEventListener("scroll", schedule, { passive: true, capture: true });
    window.addEventListener("resize", schedule);
    window.visualViewport?.addEventListener("resize", schedule);

    return () => {
      if (raf) cancelAnimationFrame(raf);
      document.removeEventListener("scroll", schedule, { capture: true });
      window.removeEventListener("resize", schedule);
      window.visualViewport?.removeEventListener("resize", schedule);
    };
  }, []);
  const videoRef = useRef<HTMLVideoElement>(null);

  // Warm-then-rewind: let the video autoplay invisibly to warm the decoder pipeline and fetch
  // eagerly (video-first — the clip is the star; the poster is only the no-blank-screen
  // fallback). Once 6 frames are painted (decoder hot), pause and seek back to 0, then reveal +
  // play — so visible playback always starts at frame 0, landing seamlessly on the matching
  // poster (the poster IS this video's first frame). Opacity is mutated via ref (no re-render).
  useEffect(() => {
    const v = videoRef.current;
    if (!v) return;
    let revealed = false;
    let handle = 0;
    const reveal = () => {
      if (revealed) return;
      revealed = true;
      v.style.opacity = "1";
      if (v.paused) v.play().catch(() => {});
    };
    const timer = setTimeout(reveal, 2500); // safety fallback
    if (typeof v.requestVideoFrameCallback === "function") {
      let count = 0;
      const cb = () => {
        count++;
        if (count >= 6) {
          v.pause();
          v.currentTime = 0;
          requestAnimationFrame(reveal); // ensure seek lands before opacity flip
          return;
        }
        handle = v.requestVideoFrameCallback(cb);
      };
      handle = v.requestVideoFrameCallback(cb);
    }
    return () => {
      clearTimeout(timer);
      if (handle && typeof v.cancelVideoFrameCallback === "function") v.cancelVideoFrameCallback(handle);
    };
  }, []);
  // <video> runs its resource-selection algorithm exactly once, when the element is inserted —
  // unlike <picture> it never re-evaluates the <source media> attributes again. A viewport that
  // crosses the 767px boundary after load (phone rotation, window resize, browser zoom) is left
  // holding the wrong clip, and object-cover crops the portrait one hard on a landscape box.
  // Re-select by hand on a real breakpoint flip: load() re-reads the sources and restores the
  // autoplay flag, so playback resumes on its own — unless the visitor had deliberately paused.
  useEffect(() => {
    if (!hero.videoMobile) return;
    const mql = window.matchMedia("(max-width: 767px)");
    const onChange = () => {
      const v = videoRef.current;
      if (!v) return;
      const wasPaused = v.paused;
      v.load();
      if (wasPaused) v.addEventListener("loadeddata", () => v.pause(), { once: true });
    };
    mql.addEventListener("change", onChange);
    return () => mql.removeEventListener("change", onChange);
  }, [hero.videoMobile]);

  const line1Ref = useRef<HTMLSpanElement>(null);
  const line2Ref = useRef<HTMLSpanElement>(null);
  const line3Ref = useRef<HTMLSpanElement>(null);
  const { t, tl } = useLanguage();

  // Measure all title lines, find the widest, then stretch the narrower ones via letter-spacing.
  // Must wait for the serif webfont — measuring against fallback-font metrics produces wrong widths.
  useLayoutEffect(() => {
    const sync = () => {
      [line1Ref, line2Ref, line3Ref].forEach(r => { if (r.current) r.current.style.letterSpacing = ""; });
      const refs = [line1Ref, line2Ref].map(r => r.current).filter(Boolean) as HTMLSpanElement[];
      const widths = refs.map(el => el.getBoundingClientRect().width);
      const max = Math.max(...widths);
      refs.forEach((el, i) => {
        const diff = max - widths[i];
        const chars = (el.textContent ?? "").length;
        if (diff > 0 && chars > 0) el.style.letterSpacing = `${diff / chars}px`;
      });
    };
    document.fonts?.ready.then(sync).catch(() => sync());
    window.addEventListener("resize", sync);
    return () => window.removeEventListener("resize", sync);
  }, []);


  const toggleVideo = () => {
    const video = videoRef.current;
    if (!video) return;
    if (video.paused) { video.play(); setPaused(false); }
    else { video.pause(); setPaused(true); }
  };

  return (
    <section ref={sectionRef} className="relative h-svh w-full overflow-hidden bg-black">
      {/* Preload the LCP poster per device — the art-directed <picture> below can't use
          next/image's priority preload, and without it the poster is discovered late (browsers
          were preloading below-the-fold images instead, tanking LCP). media + imageSrcSet/
          imageSizes mirror the <source>/<img> exactly so the browser reuses the preload instead
          of double-fetching; React 19 hoists these <link>s into <head>. */}
      {hero.imageMobile && (
        <link
          rel="preload"
          as="image"
          href={imageLoader({ src: hero.imageMobile, width: 720, quality: 78 })}
          media="(max-width: 767px)"
          imageSrcSet={heroSrcSet(hero.imageMobile, MOBILE_WIDTHS)}
          imageSizes="100vw"
          fetchPriority="high"
        />
      )}
      <link
        rel="preload"
        as="image"
        href={imageLoader({ src: hero.imagePoster ?? hero.image, width: 1920, quality: 78 })}
        media="(min-width: 768px)"
        imageSrcSet={heroSrcSet(hero.imagePoster ?? hero.image, DESKTOP_WIDTHS)}
        imageSizes="100vw"
        fetchPriority="high"
      />
      {/* Always-on poster layer — the LCP image and the video's fallback. Art-directed like the
          <video> below: the portrait first-frame on phones, the landscape first-frame on larger
          screens. A <picture> with media <source>s makes the browser fetch exactly ONE poster
          (no post-hydration src swap, no double download); and because each poster is the exact
          first frame of the matching clip, the video reveals seamlessly on top. Raw <img> (not
          next/image) because next/image can't art-direct — URLs still go through the Netlify CDN
          via imageLoader. */}
      <picture>
        {hero.imageMobile && (
          <source
            media="(max-width: 767px)"
            srcSet={heroSrcSet(hero.imageMobile, MOBILE_WIDTHS)}
            sizes="100vw"
          />
        )}
        <img
          src={imageLoader({ src: hero.imagePoster ?? hero.image, width: 1920, quality: 78 })}
          srcSet={heroSrcSet(hero.imagePoster ?? hero.image, DESKTOP_WIDTHS)}
          sizes="100vw"
          alt={hero.imageAlt}
          fetchPriority="high"
          decoding="async"
          className="absolute inset-0 h-full w-full object-cover"
        />
      </picture>

      {hero.video && (
        <video
          ref={videoRef}
          autoPlay muted loop playsInline preload="auto"
          style={{ opacity: 0, willChange: "opacity", transform: "translateZ(0)" }}
          className="absolute inset-0 h-full w-full object-cover"
        >
          {/* Browser picks the first matching source at parse time, so the <video>
              renders in SSR and only the device-appropriate clip is fetched. */}
          {hero.videoMobile && (
            <source
              src={`${BASE_PATH}${versionedAsset(hero.videoMobile)}`}
              media="(max-width: 767px)"
              type="video/mp4"
            />
          )}
          <source src={`${BASE_PATH}${versionedAsset(hero.video)}`} type="video/mp4" />
        </video>
      )}

      {/* Soft cinematic gradient overlay */}
      <div className="absolute inset-0 bg-gradient-to-b from-black/20 via-transparent to-black/20" />

      {/* Content — visible from first paint (SSR), disappears instantly on scroll. It used to
          fade in via a post-hydration state, but that left the <h1> (the LCP element) at
          opacity:0 until hydration (~5s on throttled mobile), which was the LCP. Now it paints
          with the page; only the scroll-away transition remains. */}
      <div
        style={{ willChange: "opacity", transform: "translateZ(0)" }}
        // pb reserves the space the CTA used to occupy in this centred stack, so
        // lifting it out to absolute positioning leaves the title block exactly
        // where it was rather than letting it settle downward.
        className={`relative z-10 flex h-svh flex-col items-center justify-center px-6 pb-[82px] md:pb-[178px] text-center text-white ${atTop ? "transition-opacity duration-500" : ""} ${!atTop ? "opacity-0 pointer-events-none" : "opacity-100"}`}
      >
        {/* Logo */}
        <Image
          src="/images/logo/logo-dark.webp"
          alt="Orlowsky Discovery Hotel logo"
          width={140}
          height={140}
          priority
          className="w-24 h-24 md:w-[96px] md:h-[96px] lg:w-[108px] lg:h-[108px] mb-4 md:mb-4 drop-shadow-[0_2px_8px_rgba(0,0,0,0.4)]"
        />

        {/* Title block */}
        <h1 className="font-serif text-shadow-strong text-center">
          <span className="block text-[2.25rem] md:text-[2.25rem] lg:text-[2.5rem] tracking-[0.22em] uppercase font-light leading-none">
            <span ref={line1Ref}>{hero.titleLine1}</span>
          </span>

          <span className="block text-[2.625rem] md:text-[2.625rem] lg:text-[2.875rem] italic font-light mt-3 md:mt-3 leading-snug">
            <span ref={line2Ref}>{hero.titleLine2}</span>
          </span>

          {hero.titleLine4 && (
            <span className="block text-[2.625rem] md:text-[2.625rem] lg:text-[2.875rem] italic font-light mt-1 md:mt-2 leading-snug">
              <span ref={line3Ref}>{hero.titleLine4}</span>
            </span>
          )}

          <div className="w-fit mx-auto mt-10 md:mt-10">
            <span className="block text-xl md:text-xl lg:text-xl tracking-[0.3em] uppercase font-semibold">
              {hero.titleLine3}
            </span>

            {/* Stars aligned to width of titleLine3 */}
            <div className="relative">
              <span className="absolute right-full top-1/2 -translate-y-1/2 mr-3 block h-px w-8 bg-white/30" />
              <div
                className="mt-2 flex justify-between text-sm md:text-base translate-x-[1px] pr-[0.34rem] md:pr-[0.45rem] lg:pr-[0.56rem] text-logo-gold"
              >
                {"★ ★ ★ ★".split(" ").map((star, i) => (
                  <span key={i}>{star}</span>
                ))}
              </div>
              <span className="absolute left-full top-1/2 -translate-y-1/2 ml-3 block h-px w-8 bg-white/30" />
            </div>
          </div>
        </h1>

        {/* Subtitle */}
        <div className="mt-4 flex flex-col items-center gap-2">
          <p className="font-sans font-light text-sm md:text-sm tracking-[0.2em] uppercase text-white/95 text-shadow-strong">
            Cottages &amp; Villas
          </p>
          <p className="font-sans font-light text-xs md:text-xs tracking-[0.18em] uppercase text-white/80 text-shadow-strong">
            Bar&nbsp;·&nbsp;Restaurant&nbsp;·&nbsp;Ayurvedic Spa
          </p>
        </div>

        {/* CTA */}
        <a
          href={hero.ctaHref}
          target="_blank"
          rel="noopener noreferrer"
          // Centred in the gap between the subtitle and the scroll arrow. The
          // subtitle sits a fixed distance from the viewport's midline and the
          // arrow is pinned to the bottom, so that gap's midpoint works out to
          // 75% of viewport height plus a constant — which holds at any height,
          // unlike the fixed margin this replaces.
          className="absolute left-1/2 top-[calc(75%+72px)] md:top-[calc(75%+55px)] -translate-x-1/2 -translate-y-1/2 inline-block whitespace-nowrap bg-black/15 hover:bg-black/30 text-white border border-white/60 hover:border-white rounded-full font-sans font-light px-7 py-2.5 md:px-8 md:py-3 tracking-[0.22em] uppercase text-[11px] md:text-xs transition-all duration-500 focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-offset-2 drop-shadow-[0_2px_8px_rgba(0,0,0,0.9)]"
        >
          {t(hero.cta)}
        </a>
      </div>

      {/* Scroll indicator */}
      <div className={`${atTop ? "transition-opacity duration-500" : ""} ${!atTop ? "opacity-0" : ""}`}>
        <m.div
          className="absolute bottom-4 md:bottom-5 left-1/2 -translate-x-1/2 z-10"
          animate={{ y: [0, 8, 0] }}
          transition={{ duration: 1.6, ease: "easeInOut", repeat: Infinity, repeatDelay: 0.4 }}
        >
          <svg width="28" height="16" viewBox="0 0 28 16" fill="none" aria-hidden="true">
            <polyline points="2,2 14,13 26,2" stroke="white" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" opacity="0.7" />
          </svg>
        </m.div>
      </div>

      {/* Video pause toggle — quiet by default, brightens on hover/focus so it
          stays noticeable to a new visitor without competing with hero content. */}
      {hero.video && (
        <button
          onClick={toggleVideo}
          aria-label={paused ? tl.hero.playVideo : tl.hero.pauseVideo}
          className="absolute bottom-6 right-8 -mr-2 md:bottom-8 z-10 p-2 text-white opacity-40 hover:opacity-100 transition-opacity duration-300 focus-visible:ring-2 focus-visible:ring-brand-teal drop-shadow-[0_1px_3px_rgba(0,0,0,0.5)]"
        >
          {paused ? <Play size={24} /> : <Pause size={24} />}
        </button>
      )}
    </section>
  );
}
